author:
  name             : "Siyuan Li"
  avatar           : "/images/profile.png"
  bio              : 
  location         : "Shanghai, China"
  employer         :
  pubmed           :
  googlescholar    : "https://scholar.google.com/citations?user=7w89fusAAAAJ"
  email            : "siyuanli@sjtu.edu.cn"
  researchgate     : 
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : 
  google_plus      :
  keybase          :
  instagram        :
  impactstory      : 
  lastfm           :
  linkedin         : 
  dblp             : 
  orcid            : "0000-0002-5045-9472"
  pinterest        :
  soundcloud       :
  stackoverflow    : 
  steam            :
  tumblr           :
  twitter          : 
  vine             :
  weibo            :
  xing             :
  youtube          :
  wikipedia        :
